"""empty message

Revision ID: 6dfa9ab1c284
Revises: c5f13b64a266
Create Date: 2019-01-13 07:02:22.858255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfa9ab1c284'
down_revision = 'c5f13b64a266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_test', ['test_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_test', type_='unique')
    # ### end Alembic commands ###
