"""empty message

Revision ID: c5f13b64a266
Revises: 8e4b1dd92828
Create Date: 2019-01-13 06:48:02.275530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f13b64a266'
down_revision = '8e4b1dd92828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_test', sa.Column('correct_answers', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('negative_score', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('no_answers', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('positive_score', sa.Integer(), nullable=False))
    op.add_column('user_test', sa.Column('test_taken_on_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_test', sa.Column('wrong_answers', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_test', 'wrong_answers')
    op.drop_column('user_test', 'test_taken_on_date')
    op.drop_column('user_test', 'positive_score')
    op.drop_column('user_test', 'no_answers')
    op.drop_column('user_test', 'negative_score')
    op.drop_column('user_test', 'correct_answers')
    # ### end Alembic commands ###
