"""empty message

Revision ID: d37cb6f3095d
Revises: b31d6df8c7fe
Create Date: 2019-01-12 23:55:26.840487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd37cb6f3095d'
down_revision = 'b31d6df8c7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'test_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.add_column('user', sa.Column('is_admin', sa.Integer(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('user', 'is_admin')
    op.alter_column('test', 'test_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
