"""empty message

Revision ID: d51df56035f0
Revises: 6dfa9ab1c284
Create Date: 2019-01-14 06:20:44.596534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51df56035f0'
down_revision = '6dfa9ab1c284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('section', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'section')
    # ### end Alembic commands ###
