"""empty message

Revision ID: f132689e5ebe
Revises: 
Create Date: 2019-01-26 07:00:53.445906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f132689e5ebe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_test', sa.Column('attempted_ques', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_test', 'attempted_ques')
    # ### end Alembic commands ###
